image: maven:3.9.1-amazoncorretto-17

variables:
  MAVEN_CLI_OPTS: "-s .m2/settings.xml --batch-mode"
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"

before_script:
  - mkdir .m2
  - cat $MVN_SETTINGS > .m2/settings.xml

build:
  stage: build
  script:
    - mvn $MAVEN_CLI_OPTS package
  artifacts:
    paths:
      - urlique-server/target/urlique-server-*/urlique-server-*/*

deploy:
  stage: deploy
  script:
    - mvn $MAVEN_CLI_OPTS deploy