services:
  urlique-server:
    build: ./urlique-server
    ports:
      - 8085:8080
    volumes:
      - ./configs/application.properties:/app/application.properties
      - ./configs:/app/configs/
      - ./urlique-server/target/urlique-server-1.0-SNAPSHOT-application/urlique-server-1.0-SNAPSHOT/lib:/app/lib